package com.crucix.android.data

data class CrucixConfig(
    // Server connection
    val serverUrl: String = "http://192.168.1.100:3117",

    // Core data sources (free, highest priority)
    val fredApiKey: String = "",
    val firmsMapKey: String = "",
    val eiaApiKey: String = "",

    // Extended data sources
    val acledEmail: String = "",
    val acledPassword: String = "",
    val aisstreamApiKey: String = "",
    val adsbApiKey: String = "",

    // LLM integration
    val llmProvider: String = "",        // anthropic | openai | gemini | codex
    val llmApiKey: String = "",
    val llmModel: String = "",

    // Telegram
    val telegramBotToken: String = "",
    val telegramChatId: String = "",
    val telegramChannels: String = "",
    val telegramPollInterval: String = "5000",

    // Discord
    val discordBotToken: String = "",
    val discordChannelId: String = "",
    val discordGuildId: String = "",
    val discordWebhookUrl: String = "",

    // Server config
    val port: String = "3117",
    val refreshIntervalMinutes: String = "15"
) {
    fun toEnvString(): String {
        val lines = mutableListOf<String>()
        lines.add("# Crucix Configuration")
        lines.add("# Generated by Crucix Android App")
        lines.add("")

        lines.add("# ─── Server Config ───────────────────────────────")
        if (port.isNotBlank()) lines.add("PORT=$port")
        if (refreshIntervalMinutes.isNotBlank()) lines.add("REFRESH_INTERVAL_MINUTES=$refreshIntervalMinutes")
        lines.add("")

        lines.add("# ─── Core Data Sources (free) ────────────────────")
        if (fredApiKey.isNotBlank()) lines.add("FRED_API_KEY=$fredApiKey")
        if (firmsMapKey.isNotBlank()) lines.add("FIRMS_MAP_KEY=$firmsMapKey")
        if (eiaApiKey.isNotBlank()) lines.add("EIA_API_KEY=$eiaApiKey")
        lines.add("")

        lines.add("# ─── Extended Data Sources ───────────────────────")
        if (acledEmail.isNotBlank()) lines.add("ACLED_EMAIL=$acledEmail")
        if (acledPassword.isNotBlank()) lines.add("ACLED_PASSWORD=$acledPassword")
        if (aisstreamApiKey.isNotBlank()) lines.add("AISSTREAM_API_KEY=$aisstreamApiKey")
        if (adsbApiKey.isNotBlank()) lines.add("ADSB_API_KEY=$adsbApiKey")
        lines.add("")

        lines.add("# ─── LLM Integration (optional) ──────────────────")
        if (llmProvider.isNotBlank()) lines.add("LLM_PROVIDER=$llmProvider")
        if (llmApiKey.isNotBlank()) lines.add("LLM_API_KEY=$llmApiKey")
        if (llmModel.isNotBlank()) lines.add("LLM_MODEL=$llmModel")
        lines.add("")

        lines.add("# ─── Telegram Integration (optional) ─────────────")
        if (telegramBotToken.isNotBlank()) lines.add("TELEGRAM_BOT_TOKEN=$telegramBotToken")
        if (telegramChatId.isNotBlank()) lines.add("TELEGRAM_CHAT_ID=$telegramChatId")
        if (telegramChannels.isNotBlank()) lines.add("TELEGRAM_CHANNELS=$telegramChannels")
        if (telegramPollInterval.isNotBlank() && telegramPollInterval != "5000")
            lines.add("TELEGRAM_POLL_INTERVAL=$telegramPollInterval")
        lines.add("")

        lines.add("# ─── Discord Integration (optional) ──────────────")
        if (discordBotToken.isNotBlank()) lines.add("DISCORD_BOT_TOKEN=$discordBotToken")
        if (discordChannelId.isNotBlank()) lines.add("DISCORD_CHANNEL_ID=$discordChannelId")
        if (discordGuildId.isNotBlank()) lines.add("DISCORD_GUILD_ID=$discordGuildId")
        if (discordWebhookUrl.isNotBlank()) lines.add("DISCORD_WEBHOOK_URL=$discordWebhookUrl")

        return lines.joinToString("\n")
    }

    fun getConfiguredKeyCount(): Int {
        return listOf(
            fredApiKey, firmsMapKey, eiaApiKey,
            acledEmail, aisstreamApiKey, adsbApiKey,
            llmApiKey, telegramBotToken, discordBotToken, discordWebhookUrl
        ).count { it.isNotBlank() }
    }
}
